apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret
  resources:
    limits:
      cpu: '3'
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 1700Mi
  http:
    httpEnabled: true
    httpPort: 8080
  proxy:
    headers: xforwarded
  hostname:
    hostname: keycloak.apps.cluster-9qn7g.9qn7g.sandbox2382.opentlc.com
  ingress:
    className: openshift-default
    enabled: true
  additionalOptions:
    - name: log-console-output
      value: json
    - name: metrics-enabled
      value: 'true'
    - name: health-enabled
      value: 'true'
  features:
    enabled:
      - preview
  db:
    database: keycloakdb
    host: keycloak-postgresql.keycloak.svc.cluster.local
    passwordSecret:
      key: password
      name: keycloak-db-secret
    port: 5432
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  instances: 2
