apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  {{- if .Values.keycloakLabels }}
  labels:
    {{- with .Values.keycloakLabels }}
      {{- toYaml . | nindent 4 }}
     {{- end }}
  {{- end }}
  {{- if .Values.keycloakAnnotations }}
  annotations:
    {{- with .Values.keycloakAnnotations }}
      {{- toYaml . | nindent 4 }}
     {{- end }}
  {{- end }}
spec:
  {{- $keycloakGlobal := dict }}
  {{- if and .Values.global .Values.global.keycloak }}
  {{- $keycloakGlobal = .Values.global.keycloak }}
  {{- end }}
  {{- $keycloak := (merge .Values.keycloak $keycloakGlobal) | required ".Values.keycloak is required." -}}
  {{- with $keycloak }}
    {{- toYaml . | nindent 2 }}
   {{- end }}
