apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  bootstrapAdmin:
    user:
      secret: keycloak-admin-secret
  resources:
    limits:
      cpu: '4'
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 1700Mi
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
  proxy:
    headers: xforwarded
  hostname:
    hostname: keycloak.apps.cluster-9qn7g.9qn7g.sandbox2382.opentlc.com
  ingress:
    className: openshift-default
    enabled: true
  additionalOptions:
    - name: log-console-output
      value: default
    - name: log-level
      value: "info,org.keycloak.events:trace"
  db:
    database: keycloakdb
    host: keycloak-postgresql.keycloak.svc.cluster.local
    passwordSecret:
      key: password
      name: keycloak-db-secret
    port: 5432
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  instances: 1
  image: quay.io/rhn_gps_mileri/rhbk:26_0
  startOptimized: true
