global:
  keycloak:
    additionalOptions:
      - name: log-console-output
        value: default
      - name: log-level
        value: info,org.keycloak.events:trace
    bootstrapAdmin:
      user:
        secret: keycloak-admin-secret
    db:
      passwordSecret:
        key: password
        name: keycloak-db-secret
      port: 5432
      usernameSecret:
        key: username
        name: keycloak-db-secret
      vendor: postgres
    http:
      httpEnabled: true
      httpPort: 8080
      httpsPort: 8443
    ingress:
      className: openshift-default
      enabled: false
    proxy:
      headers: xforwarded
    startOptimized: false
